server:
  port: 8001

spring:
  datasource:
    username: root
    password: 981203Long!
    url: jdbc:mysql://localhost:3306/corporate_website?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: 981203long
    timeout: 5000

mybatis:
  mapper-locations: classpath:./mapper_xml/*.xml
  type-aliases-package: com.datasource.entities

